"""Code Materializer Agent - Translates strategy specs to executable code."""

from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

import ast

from hrp.agents.research_agents import ResearchAgent
from hrp.research.lineage import log_event, EventType


@dataclass
class CodeMaterializerConfig:
    """Configuration for Code Materializer agent."""

    hypothesis_ids: list[str] | None = None
    validate_syntax: bool = True
    enforce_pit: bool = True
    output_dir: str = "hrp/strategies/generated"


class CodeMaterializer(ResearchAgent):
    """
    Translates strategy specifications into executable code.

    Performs mechanical translation WITHOUT:
    - Interpreting economic rationale
    - Optimizing signal logic
    - Choosing features
    - Judging performance
    """

    ACTOR = "agent:code-materializer"
    DEFAULT_JOB_ID = "code_materializer"

    def __init__(
        self,
        hypothesis_ids: list[str] | None = None,
        config: CodeMaterializerConfig | None = None,
        api: Any = None,
    ):
        super().__init__(
            job_id=self.DEFAULT_JOB_ID,
            actor=self.ACTOR,
            dependencies=[],
        )
        self.hypothesis_ids = hypothesis_ids
        self.config = config or CodeMaterializerConfig()
        self.api = api

    def execute(self) -> dict[str, Any]:
        """Execute code materialization for hypotheses."""
        from hrp.api.platform import PlatformAPI

        api = self.api or PlatformAPI()
        hypotheses = self._get_hypotheses(api)

        results = []
        for hypothesis in hypotheses:
            result = self._materialize_hypothesis(hypothesis)
            results.append(result)

            # Log completion event
            self._log_agent_event(
                event_type=EventType.CODE_MATERIALIZER_COMPLETE,
                hypothesis_id=hypothesis["hypothesis_id"],
                details={
                    "code_generated": result["code_generated"],
                    "syntax_valid": result["syntax_valid"],
                    "output_path": result.get("output_path"),
                },
            )

        return {
            "hypotheses_processed": len(results),
            "code_generated": sum(1 for r in results if r["code_generated"]),
            "syntax_valid": sum(1 for r in results if r["syntax_valid"]),
        }

    def _get_hypotheses(self, api) -> list[dict]:
        """Get hypotheses to materialize."""
        if self.hypothesis_ids:
            return [api.get_hypothesis(hid) for hid in self.hypothesis_ids]
        # Get all hypotheses with strategy specs and no code
        return api.list_hypotheses(status="testing")  # Simplified

    def _materialize_hypothesis(self, hypothesis: dict) -> dict:
        """Materialize a single hypothesis."""
        hypothesis_id = hypothesis["hypothesis_id"]
        strategy_spec = hypothesis.get("metadata", {}).get("strategy_spec", {})

        # Generate code from spec
        code = self._generate_code(strategy_spec)

        # Validate syntax if enabled
        syntax_valid = True
        if self.config.validate_syntax:
            syntax_valid = self._validate_syntax(code)

        # Write to file
        output_path = None
        if syntax_valid:
            output_path = self._write_code(hypothesis_id, code)

        return {
            "hypothesis_id": hypothesis_id,
            "code_generated": True,
            "code": code,
            "syntax_valid": syntax_valid,
            "output_path": output_path,
        }

    def _generate_code(self, spec: dict) -> str:
        """Generate code from strategy spec."""
        signal_logic = spec.get("signal_logic", "")
        universe = spec.get("universe", "sp500")
        holding_days = spec.get("holding_period_days", 20)

        # Simple translation logic
        code = f"""# Auto-generated by Code Materializer
# DO NOT EDIT MANUALLY

from hrp.strategies.base import StrategyBase

class GeneratedStrategy(StrategyBase):
    def __init__(self):
        self.universe = "{universe}"
        self.holding_period_days = {holding_days}

    def generate_signals(self, prices, features):
        # Signal: {signal_logic}
        # TODO: Translate to executable code
        pass
"""
        return code

    def _validate_syntax(self, code: str) -> bool:
        """Validate Python syntax."""
        try:
            ast.parse(code)
            return True
        except SyntaxError:
            return False

    def _write_code(self, hypothesis_id: str, code: str) -> str:
        """Write generated code to file."""
        output_dir = Path(self.config.output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)

        output_path = output_dir / f"{hypothesis_id}.py"
        output_path.write_text(code)

        return str(output_path)
